/* Automatically generated by configure */
/* Generated: Mon Dec 15 19:24:57 PST 2025 */

#ifndef _COMPILER_DETAILS_H
#define _COMPILER_DETAILS_H
#undef BIG_ENDIAN
#undef LITTLE_ENDIAN
#define LITTLE_ENDIAN
#endif /* _COMPILER_DETAILS_H */
