name = "MEX-SAMPLE"
title = "MEX SAMPLES (%t mins)"
header_file = "display/screens/mexinfo"
header_types = ["Novice", "Regular", "Expert"]
menu_file = ""
menu_types = []
menu_length = 0
menu_color = -1
option_width = 0

[[option]]
command = "MEX"
arguments = "scripts/userlist"
priv_level = "Demoted"
description = "1 Userlist"
key_poke = ""
modifiers = []

[[option]]
command = "MEX"
arguments = "scripts/callers"
priv_level = "Demoted"
description = "2 Callers"
key_poke = ""
modifiers = []

[[option]]
command = "MEX"
arguments = "scripts/card"
priv_level = "Demoted"
description = "3 21-like game"
key_poke = ""
modifiers = []

[[option]]
command = "MEX"
arguments = "scripts/class"
priv_level = "Demoted"
description = "4 User class info"
key_poke = ""
modifiers = []

[[option]]
command = "MEX"
arguments = "scripts/lastrd"
priv_level = "Demoted"
description = "5 Show lastread"
key_poke = ""
modifiers = []

[[option]]
command = "MEX"
arguments = "scripts/weather"
priv_level = "Demoted"
description = "6 Weather forecast"
key_poke = ""
modifiers = []

[[option]]
command = "MEX"
arguments = "scripts/mexchat"
priv_level = "Demoted"
description = "7 Full-screen chat"
key_poke = ""
modifiers = []

[[option]]
command = "MEX"
arguments = "scripts/jsontest"
priv_level = "Demoted"
description = "8 JSON test suite"
key_poke = ""
modifiers = []

[[option]]
command = "MEX"
arguments = "scripts/socktest"
priv_level = "Demoted"
description = "9 Weather report (wttr.in)"
key_poke = ""
modifiers = []

[[option]]
command = "MEX"
arguments = "scripts/uitest"
priv_level = "Demoted"
description = "A UI Test"
key_poke = ""
modifiers = []

[[option]]
command = "Goodbye"
arguments = ""
priv_level = "Demoted"
description = "Goodbye"
key_poke = ""
modifiers = []

[[option]]
command = "Display_Menu"
arguments = "MEX"
priv_level = "Demoted"
description = "Back"
key_poke = ""
modifiers = []
